# Generated by Django 5.2.15 on 2026-06-20 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='挑戰名稱')),
                ('description', models.TextField(verbose_name='挑戰描述')),
                ('challenge_type', models.CharField(choices=[('daily', '每日挑戰'), ('weekly', '每週挑戰')], default='daily', max_length=10, verbose_name='挑戰類型')),
                ('start_at', models.DateTimeField(verbose_name='開始時間')),
                ('end_at', models.DateTimeField(verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('share_enabled', models.BooleanField(default=True, verbose_name='允許分享')),
                ('points_per_checkin', models.IntegerField(default=10, verbose_name='每次打卡基本分數')),
                ('bonus_for_streak', models.IntegerField(default=5, verbose_name='連續打卡額外紅利')),
            ],
            options={
                'verbose_name': '挑戰',
                'verbose_name_plural': '挑戰列表',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='打卡日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='實際寫入時間')),
                ('score_earned', models.IntegerField(default=0, verbose_name='本次獲得分數')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='challenges.challenge', verbose_name='挑戰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '打卡紀錄',
                'verbose_name_plural': '打卡紀錄',
                'ordering': ['-check_in_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge', 'check_in_date'), name='unique_daily_checkin')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('current_streak', models.IntegerField(default=0, verbose_name='目前連續打卡天數')),
                ('total_points', models.IntegerField(default=0, verbose_name='總分')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已完成'), ('dropped', '已退出')], default='active', max_length=20, verbose_name='狀態')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge', verbose_name='挑戰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '挑戰參與紀錄',
                'verbose_name_plural': '挑戰參與紀錄',
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='unique_participant')],
            },
        ),
    ]
