# Generated by Django 5.2.15 on 2026-08-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='挑戰標題')),
                ('description', models.TextField(verbose_name='挑戰說明')),
                ('challenge_type', models.CharField(choices=[('daily', '每日挑戰'), ('weekly', '每週挑戰')], default='daily', max_length=20, verbose_name='挑戰類型')),
                ('start_at', models.DateTimeField(verbose_name='開始時間')),
                ('end_at', models.DateTimeField(verbose_name='結束時間')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否進行中')),
                ('share_enabled', models.BooleanField(default=True, verbose_name='啟用分享')),
                ('points_per_checkin', models.PositiveIntegerField(default=10, verbose_name='每次打卡基礎分數')),
                ('bonus_for_streak', models.PositiveIntegerField(default=5, verbose_name='連續打卡額外加分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '挑戰活動',
                'verbose_name_plural': '挑戰活動清單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(db_index=True, verbose_name='打卡所屬日期')),
                ('score_earned', models.PositiveIntegerField(default=0, verbose_name='本次獲得積分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='打卡時間')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='challenges.challenge', verbose_name='挑戰活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '打卡紀錄',
                'verbose_name_plural': '打卡紀錄明細',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge', 'check_in_date'), name='unique_daily_user_challenge_checkin')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='當前連續打卡天數')),
                ('total_points', models.PositiveIntegerField(db_index=True, default=0, verbose_name='總累積積分')),
                ('status', models.CharField(choices=[('active', '進行中'), ('completed', '已完成'), ('left', '已退出')], default='active', max_length=20, verbose_name='狀態')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='challenges.challenge', verbose_name='挑戰活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '參與紀錄',
                'verbose_name_plural': '參與紀錄名冊',
                'ordering': ['-total_points', '-current_streak'],
                'constraints': [models.UniqueConstraint(fields=('user', 'challenge'), name='unique_user_challenge_participant')],
            },
        ),
    ]
